src/event.js
test/event-fixHooks.html
test/event-props.html
test/event.js
test/iframeTest.js

Fixes #190
The single hooks iframe test was getting hairy so the jQuery.event.props test was moved into a separate test.

Event: Warn on fixHooks case when it has no props and only filter

---

build/release.js

Currently until the directory is manually created:
```
$ node build/release.js 3.0.1
Current version is 3.0.1-pre; generating release 3.0.1
(...)
Copying dist/jquery-migrate.js to CDN/jquery-migrate-3.0.1.js
Error: ENOENT: no such file or directory, open 'CDN/jquery-migrate-3.0.1.js'
at Object.fs.openSync (fs.js:652:18)
```

Build: Make release script create CDN directory if missing

---

src/offset.js
test/offset.js

Fixes #330 .
`offset` should return `undefined` instead of `{top:0,left:0}` for non DOM element.

Offset: fix wrong origin value

---

README.md
src/migrate.js
test/attributes.js
test/core.js
test/event.js
test/testinit.js

This commit introduces a new API, `jQuery.migrateDeduplicateWarnings`, set to
`true` by default but set to `false` in tests. This allows a more reliable
testing of bigger code blocks wrapped in a single `expectWarning` helper.
The commit also leverages this new behavior to simplify `jQuery.trim` tests.
Ref gh-331

Core:Tests: Add jQuery.migrateDeduplicateWarnings; don't dedupe in tests

---

Gruntfile.js
build/tasks/testswarm.js
package-lock.json
package.json
test/testinit.js

Having separate test runs for those jQuery lines is necessary as they support
different browsers. Android 4.0 fails hard when run against jQuery master code.
A git.min version was also added to aid manual testing.
I've already modified Jenkins jobs to adhere to what this PR does. I renamed the existing "jQuery Migrate" to "jQuery Migrate - 4.x core" & created a new "jQuery Migrate - 3.x core" job. Both jobs will now fire for every new Migrate commit.
I run a test run on my fork and both jobs passed:
jQuery Migrate - 4.x core: http://swarm.jquery.org/job/9632
jQuery Migrate - 3.x core: http://swarm.jquery.org/job/9633

Build: Test on jQuery 4.x separately to jQuery 3.x

---

src/css.js
test/css.js
warnings.md

CSS: Warn and fill .css(name, Number)

---

.travis.yml

That will resolve Travis config warnings; see e.g.:
https://travis-ci.org/github/jquery/jquery-migrate/jobs/674773008/config

Build: Remove a deprecated `sudo` key in the Travis config

---

.eslintrc-browser.json
.eslintrc-node.json
.eslintrc.json
Gruntfile.js
build/release.js
dist/.eslintrc.json
package-lock.json
package.json
src/.eslintrc.json
src/compareVersions.js
src/core.js
src/css.js
src/data.js
src/effects.js
src/intro.js
test/.eslintrc.json
test/ajax.js
test/core.js
test/css.js
test/deferred.js
test/effects.js
test/event.js
test/offset.js

The new ESLint setup is largely based on the current jQuery Core one.

Build: Improve ESLint configuration, check all test files as well

---

.eslintignore
.eslintrc-browser.json
.eslintrc-node.json
.gitignore
Gruntfile.js
build/tasks/build.js
dist/.eslintrc.json
package-lock.json
package.json
src/.eslintrc.json
src/jquery/ajax.js
src/jquery/attributes.js
src/jquery/core.js
src/jquery/css.js
src/jquery/data.js
src/jquery/deferred.js
src/jquery/effects.js
src/jquery/event.js
src/jquery/manipulation.js
src/jquery/offset.js
src/jquery/serialize.js
src/jquery/traversing.js
src/main.js
src/migrate.js
src/outro.js
src/utils.js
src/wrapper.js
test/data/compareVersions.js
test/index.html

The new Rollup-based build system is a very simplified version of the jQuery
one, without all the complex custom compilation aspects.
Apart from that, `grunt-compare-size` was added. While we don't care about size in Migrate to the same level as in Core, it's still good to see the impact of some changes, especially when refactoring existing code.
-1 byte compared to `master` - while the new `"use strict"` adds 1 byte, deduplication of two identical `camelCase` functions reduces the size.

Build: Migrate sources to ES modules, use a Rollup-based build system

---

Gruntfile.js
package-lock.json
package.json
src/jquery/ajax.js
src/jquery/deferred.js
src/jquery/effects.js
src/jquery/serialize.js
test/ajax.js
test/deferred.js
test/effects.js
test/event-lateload.html
test/event.js
test/serialize.js
test/testinit.js

While it'd be hard for Migrate to support all the possible jQuery builds,
the slim build is special as it's officially maintained by the jQuery team,
published to npm & uploaded to CDNs.
This commit adds support for the jQuery slim build in jQuery 3.0.0 & newer.
The slim build is now tested next to the regular one.
Fixes #345

Core: Support the jQuery slim build

---

src/jquery/css.js
test/css.js

Relying on numerical values for most CSS properties having `"px"` auto-appended
when set via `.css( prop, value )` is deprecated. So far, Migrate was warning
for number values for all CSS properties with the exception of the ones to which
jQuery 4.x will still auto-append `"px"`. However, if the used jQuery version
contains the property as a key in `jQuery.cssNumber`, it will already skip
the `"px"` auto-appending behavior, exactly as jQuery 4.x will. This commit
removes a warning in such cases.
This change will help jQuery UI from not triggering Migrate warnings.

CSS: Don't warn for number values when prop in jQuery.cssNumber

---

build/tasks/testswarm.js

We already use separate browser sets to be able to test with jQuery 3.x & 4.x.
The comment that we need separate jobs no longer applies - we already have them.

Build: Remove an obsolete comment

---

package-lock.json

So far, only the one in package.json got updated. That means
each `npm install` leaves the repository in a dirty state
by updating that field.

Build: Update the version in package-lock.json

---

test/iframeTest.js
test/migrate.js

We no longer test on PhantomJS but on Chrome Headless instead so disabling the
warning logs didn't have any effect. On the other hand, it looks like console
output from Chrome Headless is already silenced.

Build: Remove the migrateMute setter in PhantomJS in tests

---

src/jquery/offset.js
test/offset.js

Changes:
* `.offset()` works on `document.documentElement`
* `.offset()` setter on an empty object returns the source object, not undefined
* `.offset()` setter on a disconnected node returns the source object, not
`{ top: 0, left: 0 }`

Offset: Fix the offset patch

---

test/offset.js

`.offset()` in jQuery 3.0.0-3.1.1 sometimes returns an object with more than
just `top` & `left` properties. This was fixed in jQuery 3.2.0. Since we're not
in a business of fixing older jQuery versions here, this commit updates the test
instead.
Ref jquery/jquery#3367
Ref gh-352
See the failures at http://swarm.jquery.org/job/9837.

Tests: Fix offset tests in jQuery 3.0-3.1

---

src/jquery/offset.js
test/offset.js
warnings.md

The initial decision to not support disconnected elements as input to the
`.offset()` getter was reversed after feedback from jQuery UI (see jquery/jquery#2310).
Since jQuery now ensures disconnected element get `{ left: 0, top: 0 }` from
this method via unit tests it doesn't make sense to warn against such usage.
This change is the only remaining one in Migrate & UI that's required for UI
to trigger no Migrate warnings when running its test suite.
Ref jquery/jquery#2310
Ref jquery/jquery#2396

Offset: Don't warn against usage on disconnected elements

---

warnings.md

The previous replacement:
```js
text == null ? "" : text.trim()
```
didn't account for non-`null` non-string input, e.g. numbers.

Docs: Update jQuery.trim warning text

---

src/jquery/css.js
test/css.js

jQuery ~~3.3.0~~ 1.9 added support for array input to the `.css()` method; so far
Migrate was crashing with such input.
Fixes gh-357

CSS: Don't break `.css( array )`

---

test/css.js

line-height used value is measured in pixels in IE & old Firefox, let's use
z-index instead.
Ref gh-356
See http://swarm.jquery.org/job/9882

Tests: Fix CSS tests in IE & old Firefox

---

package-lock.json
package.json

The previous version, 1.1.1 had a critical bug that makes it not submit
`runUrls` properly. It is fixed in 1.1.2.
Ref gh-365
Ref jzaefferer/node-testswarm#17

Build: Update the npm testswarm package

---

warnings.md

The warning has been updated in code in gh-348 but not in warnings.md.
Ref gh-348

Docs: Update the warning against number values in jQuery.fn.css

---

CONTRIBUTING.md
Gruntfile.js
src/jquery/ajax.js
test/.eslintrc.json
test/ajax.js
test/index.html
test/migrate.js
test/testinit.js

Fixes gh-372
Ref jquery/jquery#1799
Ref jquery/jquery#3376
Ref jquery/jquery#4754

Ajax: Warn against automatic JSON-to-JSONP promotion

---

src/jquery/core.js
test/core.js

…yVersionSince( "3.3.0" ) ) {" condition.  https://github.com/jquery/jquery-migrate/issues/370
https://github.com/jquery/jquery-migrate/issues/370#issuecomment-662545742

Core: Warn against jQuery.isArray in jQuery >=3.2, not 3.3 

---

src/jquery/css.js
test/css.js

Don't assume that the name is a string when the value is a number. Doing so will throw an exception.
See an example using jQuery UI Slider: https://jsfiddle.net/mweichert/784kjmoh/17/
Closes #404

CSS: Don't throw when value is number and name is object

---

.gitignore
.npmignore
Gruntfile.js
package-lock.json
package.json
test/index.html

In c12e1ab660ac14cb1564d1f04121ef21e7b9094b, we removed the `external` directory
in favor of loading some files directly from `node_modules`. This works fine
locally but when deploying code for tests, this makes it impossible to not
deploy `node_modules` as well. To avoid the issue, this change restores usage
of the `external` directory.
One change is that we no longer commit this directory to the repository, its
only purpose is to have clear isolation from `node_modules`.
Ref jquery/jquery#4865

Build: Restore the external directory

---

test/event-lateload.html
test/index.html

gh-419 missed a few occurrences. It was overlooked as Chrome & Firefox didn't
fail any tests because of the missing CSS but IE did, see:
http://swarm.jquery.org/job/11000
Ref gh-419

Build: Remove remaining occurrences of node_modules in test HTML files

---

warnings.md

Most warnings were using level 3 headers but some used header 4 ones. They now
all use the level 3 ones.

Docs: Make all header levels in warnings.md the same

---

src/jquery/css.js
test/css.js

When used against jQuery Git (future jQuery 4), there were warnings when
`.css()` was used against `z-index` with a number value. This didn't make sense
as `z-index` never had `px` auto-appended. Commit
d25ecd68777e4be1185b61e07eb81dce2cfd56d6 was supposed to solve a similar problem
but it only worked fine for `3.x`.
To make the warning not show up when used with jQuery >=4 we need to fill in
`jQuery.cssNumber` with the latest version from jQuery 3.x so that the same
properties are allowed to have number values used with `.css()`.
With this PR, jQuery UI with jQuery git & jQuery Migrate shows no Migrate
warnings, similarly to what's already the case when jQuery 3.x-git is used.
Fixes gh-438

CSS: Don't warn against `.css( "z-index", numberValue )` in jQuery >=4

---

warnings.md

The warning landed in gh-376 but I forgot to document it.
Fixes gh-443
Ref gh-376

Docs: Document the warning about the JSON-to-JSONP auto-promotion

---

.eslintrc.json
build/release.mjs

This is now required by the latest chalk versions.

Build: Make the release script an ES module

---

src/jquery/css.js

The current logic has a few faults:
1. Tests fail on jQuery 4.0.0-pre as internal jQuery.cssNumber accesses are
triggering warnings.
2. Tests fail in IE because it doesn't support proxies and fallbacks haven't
been set properly.
We've only noticed those issues now, trying to run Migrate tests on TestSwarm
after a longer break when they weren't firing.

CSS: Fix the logic to trigger warnings on jQuery.cssNumber access

---

src/jquery/core.js

The old implementation took O(N^2) time to trim the string when multiple adjacent spaces
were present.
For instance, consider the string "A          B" (10 spaces between A and B).
Then old regexp /[\s]+$/ would take 10 steps until it realizes the regexp does not match at position 1.
Then it would try to match the regexp at position 2, and it would take 9 steps.
Then 8 steps for position 3, ... so it would take 10*10/2 steps until it figures out the regexp does not match.
The new approach is to require "non-whitespace" char before the whitespace run, so it spends just one step for each space in the string.
Note: if `String.prototype.trim()` is good enough, then the implementation would use it.

Deprecated: Improve $.trim performance for strings with lots of whitespace

---

Gruntfile.js
package-lock.json
package.json
test/data/compareVersions.js
test/data/qunit-start.js
test/data/test-utils.js
test/data/testinit.js
test/index.html

Migrating from AMD to ES modules in gh-343 made the `raw` testing mode break as
it relied on loading raw source files. This change removes the `raw` mode in
favor of the new `esmodules` one.
Setup is different than in jQuery as jQuery uses AMD to load tests and Migrate
just loads test files directly.
When Migrate is loaded via its source ES modules, test files are loaded as
modules as well. This is necessary as module scripts behave as if loaded with
the `defer` attribute so tests need to be deferred as well.
Iframe tests are skipped in `esmodules` mode as their setup is incompatible
with the above considerations.
In addition to the above, Karma tests now also run in esmodules mode for easier
verification this mode is not broken by PRs.
Ref gh-343

Tests: Add a new esmodules flag, remove the raw one

---

Gruntfile.js
package-lock.json
package.json

We can upgrade for Migrate 4.0. It's not worth spending time on figuring out how to fix IE 9 with new UglifyJS at this point.
The `ie` option had to be renamed to `ie8` as the older version doesn't support the former. In Migrate 4 we can remove it altogether.

Build: Downgrade uglify-js to fix tests in IE 9

---

src/jquery/attributes.js
test/unit/jquery/attributes.js

Some frameworks, like AngularJS, invoke `removeAttr` on boolean attributes but only after setting the respective property to `false`. Such usage is not dangerous and would continue to work even after Migrate is removed. Therefore, only warn for `removeAttr(booleanAttribute)` if the property wasn't `false` already.
Fixes gh-471

Attributes: Don't warn against `removeAttr` if property `false`

---

warnings.md

I think that jquery.fn.unload() should have the "is deprecated and removed" label. .unload() was deprecated in jquery v1.8 and removed in v3.0 So if you get this "warning" it will not actually work once you remove the jquery migrate plugin.
Reference: https://api.jquery.com/unload/

Docs: Mark `jQuery.fn.load( [ eventData ], handler )` as removed

---

src/jquery/attributes.js

In jquery/jquery#5384, `jQuery.expr.match.bool` stopped being defined and the regex matching boolean attributes is no longer exposed. Inline it in Migrate to avoid it crashing on jQuery 4.x.
Fixes gh-495

Attributes: Fix compatibility with jQuery 4.x

---

.github/dependabot.yml
.github/workflows/node.js.yml

Changes:
1. Reference concrete hashes of actions with versions in comments
2. Update actions to recent versions
3. Set up automatic dependabot montly PRs updating actions
Fortunately, hashes with versions in comments is syntax recognized by dependabot automatic updates; we're using it with success in jQuery Core.

Build: Improve security of the GitHub Actions setup

---

.github/workflows/node.js.yml

Without this change, dependabot PRs run double checks - one set for the `push` part and one for the `pull_request` part.
Ref jquery/jquery#5353

Build: Don't run CI push workflows for dependabot branches

---

.husky/commit-msg
.husky/pre-commit
package-lock.json
package.json

Git hooks are broken since gh-512; this change fixes them by migrating to Husky as jQuery Core did.
Without this fix, even `git commit --no-verify` doesn't work; only manually deleting the `.git/hooks` directory and re-running `git commit` does.
Ref gh-512

Build: Fix git hooks

---

src/jquery/manipulation.js
test/unit/jquery/manipulation.js

This is unusual as it's not the Core API but we support this patch via a more generic API now:
```
jQuery.migrateEnablePatches( "self-closed-tags" )
```
Fixes gh-474

Manipulation: Deprecate jQuery.UNSAFE_restoreLegacyHtmlPrefilter

---

build/release.js
package-lock.json
package.json

PR gh-503 erroneously removed the `enquirer` dependency, required for the release process. Restore it.
In addition, update built-in module imports to use the `node:` prefix and add a missing "utf8" value in one `fs.readFileSync`.

Release: Fix the release script

---

build/release.js

ES modules require extensions in import paths.
The dry run:
```
node build/release.js -d 3.5.0
```
succeeded after this fix.

Release: Fix the path to `build.js`

---

.github/workflows/node.js.yml
.gitignore
dist/package.json
package-lock.json
package.json
test/node_smoke_tests/smoke_tests.cjs

PR gh-512 added the `"type": "module"` field to the top-level `package.json`, making Node-based workflows fail when trying to require Migrate as it's not exposed as ESM. To fix this, add a small `package.json` with just `"type": "commonjs"`. Also, add Node.js smoke tests as the simplest way to verify this change.
Fixes gh-523
Ref gh-512
Actions run from the base branch version, so to verify this PR I changed the base branch on my fork & I submitted a draft PR at https://github.com/mgol/jquery-migrate/pull/1. The first commit with small changes passed:
https://github.com/mgol/jquery-migrate/actions/runs/9947009305/job/27478759025?pr=1
while the second one removing the `dist/package.json` that this PR adds failed as expected:
https://github.com/mgol/jquery-migrate/actions/runs/9947022296/job …

Build: Make Migrate properly recognized as a CommonJS module in Node.js

---

warnings.md

Docs: Add an entry for `legacy-self-closed-tags` in `warnings.md`

---

src/jquery/core.js
test/unit/jquery/core.js
warnings.md

Core: Fill in & warn against $.fn.{push,sort,splice}

---

eslint.config.js
package-lock.json
test/unit/jquery/core.js

1. Change `const`s in `core.js` tests to a `var` to avoid crashes in IE 9 & 10.
2. Modify the ESLint config to require ES5 in tests.
The test failure can be viewed at https://github.com/jquery/jquery-migrate/actions/runs/10891333795/job/30228137263.

Build: Fix tests in IE 10 & 9, ensure ES5 in tests

---

src/jquery/core.js
src/jquery/selector.js
src/migrate.js
test/data/testinit.js
test/runner/flags/modules.js
test/unit/jquery/core.js
test/unit/jquery/selector.js

Also:
1. Create the selector module in Migrate.
2. Migrate some selector patches from `core` to `selector`.
Fixes gh-544

Selector: Patch & warn against legacy selector pseudos

---

eslint.config.js
src/jquery/ajax.js
test/data/ajax-jsonp-callback-name.html
test/data/jsonpScript.js
test/data/testinit.js
test/index.html
test/unit/jquery/ajax.js

So far, the patch was only warning about the automatic promotion, but it wasn't filling the behavior back to jQuery 4+. This has been fixed.

Ajax: Fill in & warn against automatic JSON-to-JSONP promotion

---

src/jquery/core.js
test/unit/jquery/core.js
warnings.md

Core: Fill in & warn against jQuery.proxy

---

build/tasks/npmcopy.js
eslint.config.js
package-lock.json
package.json
src/jquery/deferred.js
test/index.html
test/unit/jquery/deferred.js
warnings.md

The API has been replaced by `jQuery.Deferred.getErrorHook`; the legacy name will be removed in jQuery 4.0.0.
Fixes gh-483

Deferred: Fill in & warn `jQuery.Deferred.getStackHook`

---

package-lock.json
package.json
src/jquery/selector.js
test/unit/jquery/ajax.js
test/unit/jquery/deferred.js
test/unit/jquery/selector.js

~~**Note:** Please don't review the first commit, that's #551. I based it like that so that I can see the tests pass; it should be "unbased" before merging. For this reason alone I'm marking this as a draft.~~
Changes:
1. Support legacy pseudos only in jQuery 3.7.0+.
2. Downgrade sinon to a version working with IE 9+.
3. Skip cross-domain ajax tests in IE 9.
4. Skip tests requiring `jQuery.Deferred.getErrorHook` in <3.7.
5. Don't require warnings for backwards-compatible pseudos if Proxy unsupported.

Core: Fix the selector module, make CI green

---

src/jquery/attributes.js
test/unit/jquery/attributes.js
warnings.md

Restore & warn against:
* boolean attributes set to something different than their lowercase names
* boolean attributes queried when set to something different than their lowercase names
* non-boolean non-ARIA attributes set to `false`
Fixes gh-504
Ref jquery/jquery#5452
Ref jquery/api.jquery.com#1243

Attributes: Restore boolean attribute & false setter treatment from 3.x

---

src/jquery/data.js
src/migrate.js
test/data/testinit.js
test/unit/jquery/data.js
warnings.md

~~NOTE: Right now, this PR includes PR #555; only review the commit titled "Data: Patch & warn about props from Object.prototype in data objects". This PR should not be merged before #555; that's the only reason it's in a draft state.~~
Ref gh-559

Data: Patch & warn about props from Object.prototype in data objects

---

src/jquery/data.js
test/data/testinit.js
test/unit/jquery/data-jquery-compat.js
test/unit/jquery/data.js
warnings.md

~~NOTE: Right now, this PR includes PR #554; only review the commit titled "Data: Patch camelCase behavior of $.fn.data, warn about Object.prototype". This PR should not be merged before #554; that's the only reason it's in a draft state.~~
Changes:
1. Patch not only `jQuery.data()`, but also `jQuery.fn.data()`.
2. Patch `jQuery.removeData()` & `jQuery.fn.removeData()` to work in most cases
when different keys with the same camelCase representation were passed to
the data setter and later to `removeData`.
3. Warn about using properties inherited from `Object.prototype` on data
objects.

Data: Patch camelCase behavior of $.fn.data, warn about Object.prototype

---

.github/workflows/browser-tests.yml
.github/workflows/browserstack.yml
.github/workflows/node.js.yml
.gitignore
build/command.js
build/tasks/build-default.js
build/tasks/build-watch.js
build/tasks/build.js
dist-module/wrappers/jquery-migrate.node-module-wrapper.js
dist/wrappers/jquery-migrate.bundler-require-wrapper.js
eslint.config.js
package-lock.json
package.json
src/wrapper-esm.js
test/bundler_smoke_tests/lib/run-rollup.js
test/bundler_smoke_tests/lib/run-webpack.js
test/bundler_smoke_tests/lib/utils.js
test/bundler_smoke_tests/rollup-commonjs.config.js
test/bundler_smoke_tests/rollup-pure-esm.config.js
test/bundler_smoke_tests/run-jsdom-tests.js
test/bundler_smoke_tests/src-esm-commonjs/jquery-migrate-require.cjs
test/bundler_smoke_tests/src-esm-commonjs/main.js
test/bundler_smoke_tests/src-pure-esm/main.js
test/bundler_smoke_tests/test.html
test/bundler_smoke_tests/webpack.config.cjs
test/node_smoke_tests/node_smoke_tests.cjs

The Migrate setup is simpler than Core as it doesn't have the slim or factory versions, but the core ideas are similar.
Fixes gh-524
Ref jquery/jquery#5255
Ref jquery/jquery#5429

Core: Provide a package.json exports setup inspired by jQuery Core

---

src/jquery/core.js
src/main.js
test/unit/migrate.js

Also:
1. Don't warn just on access of `jQuery.fn.push`, etc., but when it's called.
2. Rename some internal methods.

Core: Make migrateWarnProp not return the prop for disabled patches

---

jtr-local.yml

There was a typo in `jtr-local.yml`, making the runs using it load with a huge query string containing all the jQuery versions listed joined.
This all meant only one jQuery version was actually tested.
Ref gh-575

Build: Make browser tests correctly run on multiple jQuery versions

---

src/jquery/data.js
src/utils.js
test/unit/jquery/data.js

Also, extract the util to patch a prototype as we'll need it in the event module as well.

Data: Patch `$._data` & `$._removeData` as well, add more tests

---

src/jquery/data.js
src/utils.js
test/unit/jquery/data.js

Also, extract the util to patch a prototype as we'll need it in the event module as well.

Data: Patch `$._data` as well

---

src/jquery/event.js
test/unit/jquery/event.js
test/unit/migrate.js
warnings.md

The API has been write-only since 1.9.0 and is going to be removed in jQuery 4.0.0.
Also:
* make it more explicit why certain patches are tested in the context of `jQuery.migrateDisablePatches` & related APIs
* fix an erroneous future tense in a few warnings

Event: Patch jQuery.event.global

---

src/jquery/core.js
test/unit/jquery/core.js
warnings.md

Core: Patch push, sort & splice in jQuery >=3.7.0

---

src/jquery/event.js
test/unit/jquery/event.js

Allow to use common `Object.prototype` properties on `jQuery.event.special` but
warn as well.
Fixes gh-542
Ref gh-573
The 4.0 version: #573

Event: Patch jQuery.event.special's prototype

---

README.md
jtr-ci.yml
jtr-local.yml
package-lock.json
package.json
test/data/testinit.js

Build: Update jQuery to 4.0.0-rc.1, update README

---

warnings.md

Because jQuery 4.0.0 will not transform attribute values in the getter, the following code changes between jQuery 3.x & 4.x:
```js
$( elem ).prop( "disabled", true );
$( elem ).attr( "disabled" );
```
In jQuery 3.x, the reported attribute value is `"disabled"`, in jQuery 4.x it will be an empty string. This may create issues when migrating so Migrate patches and warns against it.
Add a recommendation to avoid using the `.attr()` getter on boolean attrs.

Docs: Improve the solution for `boolean-attributes`

---

.github/workflows/browserstack.yml

Changes:
1. Remove Safari 17
2. Remove iOS 16
3. Add iOS 26
`3.x` version: gh-602

Build: Update browsers tested in BrowserStack
